// Copyright (c) 2005-2014 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis Tools CC gives
// permission to link this program with the Xerces-C++ library (or with
// modified versions of Xerces-C++ that use the same license as Xerces-C++),
// and distribute linked combinations including the two. You must obey
// the GNU General Public License version 2 in all respects for all of
// the code used other than Xerces-C++. If you modify this copy of the
// program, you may extend this exception to your version of the program,
// but you are not obligated to do so. If you do not wish to do so, delete
// this exception statement from your version.
//
// Furthermore, Code Synthesis Tools CC makes a special exception for
// the Free/Libre and Open Source Software (FLOSS) which is described
// in the accompanying FLOSSE file.
//

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "molsimInput.hxx"

// double_vector
// 

const double_vector::x_type& double_vector::
x () const
{
  return this->x_.get ();
}

double_vector::x_type& double_vector::
x ()
{
  return this->x_.get ();
}

void double_vector::
x (const x_type& x)
{
  this->x_.set (x);
}

void double_vector::
x (::std::unique_ptr< x_type > x)
{
  this->x_.set (std::move (x));
}

const double_vector::y_type& double_vector::
y () const
{
  return this->y_.get ();
}

double_vector::y_type& double_vector::
y ()
{
  return this->y_.get ();
}

void double_vector::
y (const y_type& x)
{
  this->y_.set (x);
}

void double_vector::
y (::std::unique_ptr< y_type > x)
{
  this->y_.set (std::move (x));
}

const double_vector::z_type& double_vector::
z () const
{
  return this->z_.get ();
}

double_vector::z_type& double_vector::
z ()
{
  return this->z_.get ();
}

void double_vector::
z (const z_type& x)
{
  this->z_.set (x);
}

void double_vector::
z (::std::unique_ptr< z_type > x)
{
  this->z_.set (std::move (x));
}


// integer_vector
// 

const integer_vector::x_type& integer_vector::
x () const
{
  return this->x_.get ();
}

integer_vector::x_type& integer_vector::
x ()
{
  return this->x_.get ();
}

void integer_vector::
x (const x_type& x)
{
  this->x_.set (x);
}

void integer_vector::
x (::std::unique_ptr< x_type > x)
{
  this->x_.set (std::move (x));
}

const integer_vector::y_type& integer_vector::
y () const
{
  return this->y_.get ();
}

integer_vector::y_type& integer_vector::
y ()
{
  return this->y_.get ();
}

void integer_vector::
y (const y_type& x)
{
  this->y_.set (x);
}

void integer_vector::
y (::std::unique_ptr< y_type > x)
{
  this->y_.set (std::move (x));
}

const integer_vector::z_type& integer_vector::
z () const
{
  return this->z_.get ();
}

integer_vector::z_type& integer_vector::
z ()
{
  return this->z_.get ();
}

void integer_vector::
z (const z_type& x)
{
  this->z_.set (x);
}

void integer_vector::
z (::std::unique_ptr< z_type > x)
{
  this->z_.set (std::move (x));
}


// cuboid
// 

const cuboid::coordinates_type& cuboid::
coordinates () const
{
  return this->coordinates_.get ();
}

cuboid::coordinates_type& cuboid::
coordinates ()
{
  return this->coordinates_.get ();
}

void cuboid::
coordinates (const coordinates_type& x)
{
  this->coordinates_.set (x);
}

void cuboid::
coordinates (::std::unique_ptr< coordinates_type > x)
{
  this->coordinates_.set (std::move (x));
}

const cuboid::particles_per_dimension_type& cuboid::
particles_per_dimension () const
{
  return this->particles_per_dimension_.get ();
}

cuboid::particles_per_dimension_type& cuboid::
particles_per_dimension ()
{
  return this->particles_per_dimension_.get ();
}

void cuboid::
particles_per_dimension (const particles_per_dimension_type& x)
{
  this->particles_per_dimension_.set (x);
}

void cuboid::
particles_per_dimension (::std::unique_ptr< particles_per_dimension_type > x)
{
  this->particles_per_dimension_.set (std::move (x));
}

const cuboid::distance_particles_type& cuboid::
distance_particles () const
{
  return this->distance_particles_.get ();
}

cuboid::distance_particles_type& cuboid::
distance_particles ()
{
  return this->distance_particles_.get ();
}

void cuboid::
distance_particles (const distance_particles_type& x)
{
  this->distance_particles_.set (x);
}

void cuboid::
distance_particles (::std::unique_ptr< distance_particles_type > x)
{
  this->distance_particles_.set (std::move (x));
}

const cuboid::mass_type& cuboid::
mass () const
{
  return this->mass_.get ();
}

cuboid::mass_type& cuboid::
mass ()
{
  return this->mass_.get ();
}

void cuboid::
mass (const mass_type& x)
{
  this->mass_.set (x);
}

void cuboid::
mass (::std::unique_ptr< mass_type > x)
{
  this->mass_.set (std::move (x));
}

const cuboid::velocity_type& cuboid::
velocity () const
{
  return this->velocity_.get ();
}

cuboid::velocity_type& cuboid::
velocity ()
{
  return this->velocity_.get ();
}

void cuboid::
velocity (const velocity_type& x)
{
  this->velocity_.set (x);
}

void cuboid::
velocity (::std::unique_ptr< velocity_type > x)
{
  this->velocity_.set (std::move (x));
}


// cuboid_cluster
// 

const cuboid_cluster::cuboid_sequence& cuboid_cluster::
cuboid () const
{
  return this->cuboid_;
}

cuboid_cluster::cuboid_sequence& cuboid_cluster::
cuboid ()
{
  return this->cuboid_;
}

void cuboid_cluster::
cuboid (const cuboid_sequence& s)
{
  this->cuboid_ = s;
}


// particle
// 

const particle::coordinates_type& particle::
coordinates () const
{
  return this->coordinates_.get ();
}

particle::coordinates_type& particle::
coordinates ()
{
  return this->coordinates_.get ();
}

void particle::
coordinates (const coordinates_type& x)
{
  this->coordinates_.set (x);
}

void particle::
coordinates (::std::unique_ptr< coordinates_type > x)
{
  this->coordinates_.set (std::move (x));
}

const particle::velocity_type& particle::
velocity () const
{
  return this->velocity_.get ();
}

particle::velocity_type& particle::
velocity ()
{
  return this->velocity_.get ();
}

void particle::
velocity (const velocity_type& x)
{
  this->velocity_.set (x);
}

void particle::
velocity (::std::unique_ptr< velocity_type > x)
{
  this->velocity_.set (std::move (x));
}

const particle::mass_type& particle::
mass () const
{
  return this->mass_.get ();
}

particle::mass_type& particle::
mass ()
{
  return this->mass_.get ();
}

void particle::
mass (const mass_type& x)
{
  this->mass_.set (x);
}

void particle::
mass (::std::unique_ptr< mass_type > x)
{
  this->mass_.set (std::move (x));
}


// particle_cluster
// 

const particle_cluster::particle_sequence& particle_cluster::
particle () const
{
  return this->particle_;
}

particle_cluster::particle_sequence& particle_cluster::
particle ()
{
  return this->particle_;
}

void particle_cluster::
particle (const particle_sequence& s)
{
  this->particle_ = s;
}


// input_particles
// 

const input_particles::particle_file_optional& input_particles::
particle_file () const
{
  return this->particle_file_;
}

input_particles::particle_file_optional& input_particles::
particle_file ()
{
  return this->particle_file_;
}

void input_particles::
particle_file (const particle_file_type& x)
{
  this->particle_file_.set (x);
}

void input_particles::
particle_file (const particle_file_optional& x)
{
  this->particle_file_ = x;
}

void input_particles::
particle_file (::std::unique_ptr< particle_file_type > x)
{
  this->particle_file_.set (std::move (x));
}

const input_particles::cuboids_file_optional& input_particles::
cuboids_file () const
{
  return this->cuboids_file_;
}

input_particles::cuboids_file_optional& input_particles::
cuboids_file ()
{
  return this->cuboids_file_;
}

void input_particles::
cuboids_file (const cuboids_file_type& x)
{
  this->cuboids_file_.set (x);
}

void input_particles::
cuboids_file (const cuboids_file_optional& x)
{
  this->cuboids_file_ = x;
}

void input_particles::
cuboids_file (::std::unique_ptr< cuboids_file_type > x)
{
  this->cuboids_file_.set (std::move (x));
}

const input_particles::cuboids_optional& input_particles::
cuboids () const
{
  return this->cuboids_;
}

input_particles::cuboids_optional& input_particles::
cuboids ()
{
  return this->cuboids_;
}

void input_particles::
cuboids (const cuboids_type& x)
{
  this->cuboids_.set (x);
}

void input_particles::
cuboids (const cuboids_optional& x)
{
  this->cuboids_ = x;
}

void input_particles::
cuboids (::std::unique_ptr< cuboids_type > x)
{
  this->cuboids_.set (std::move (x));
}

const input_particles::particles_optional& input_particles::
particles () const
{
  return this->particles_;
}

input_particles::particles_optional& input_particles::
particles ()
{
  return this->particles_;
}

void input_particles::
particles (const particles_type& x)
{
  this->particles_.set (x);
}

void input_particles::
particles (const particles_optional& x)
{
  this->particles_ = x;
}

void input_particles::
particles (::std::unique_ptr< particles_type > x)
{
  this->particles_.set (std::move (x));
}


// molsimInput
// 

const molsimInput::name_output_optional& molsimInput::
name_output () const
{
  return this->name_output_;
}

molsimInput::name_output_optional& molsimInput::
name_output ()
{
  return this->name_output_;
}

void molsimInput::
name_output (const name_output_type& x)
{
  this->name_output_.set (x);
}

void molsimInput::
name_output (const name_output_optional& x)
{
  this->name_output_ = x;
}

void molsimInput::
name_output (::std::unique_ptr< name_output_type > x)
{
  this->name_output_.set (std::move (x));
}

const molsimInput::frequency_output_optional& molsimInput::
frequency_output () const
{
  return this->frequency_output_;
}

molsimInput::frequency_output_optional& molsimInput::
frequency_output ()
{
  return this->frequency_output_;
}

void molsimInput::
frequency_output (const frequency_output_type& x)
{
  this->frequency_output_.set (x);
}

void molsimInput::
frequency_output (const frequency_output_optional& x)
{
  this->frequency_output_ = x;
}

const molsimInput::delta_t_type& molsimInput::
delta_t () const
{
  return this->delta_t_.get ();
}

molsimInput::delta_t_type& molsimInput::
delta_t ()
{
  return this->delta_t_.get ();
}

void molsimInput::
delta_t (const delta_t_type& x)
{
  this->delta_t_.set (x);
}

const molsimInput::t_end_type& molsimInput::
t_end () const
{
  return this->t_end_.get ();
}

molsimInput::t_end_type& molsimInput::
t_end ()
{
  return this->t_end_.get ();
}

void molsimInput::
t_end (const t_end_type& x)
{
  this->t_end_.set (x);
}

const molsimInput::filelocation_type& molsimInput::
filelocation () const
{
  return this->filelocation_.get ();
}

molsimInput::filelocation_type& molsimInput::
filelocation ()
{
  return this->filelocation_.get ();
}

void molsimInput::
filelocation (const filelocation_type& x)
{
  this->filelocation_.set (x);
}

void molsimInput::
filelocation (::std::unique_ptr< filelocation_type > x)
{
  this->filelocation_.set (std::move (x));
}


#include <xsd/cxx/xml/dom/parsing-source.hxx>

// double_vector
//

double_vector::
double_vector (const x_type& x,
               const y_type& y,
               const z_type& z)
: ::xml_schema::type (),
  x_ (x, this),
  y_ (y, this),
  z_ (z, this)
{
}

double_vector::
double_vector (const double_vector& x,
               ::xml_schema::flags f,
               ::xml_schema::container* c)
: ::xml_schema::type (x, f, c),
  x_ (x.x_, f, this),
  y_ (x.y_, f, this),
  z_ (x.z_, f, this)
{
}

double_vector::
double_vector (const ::xercesc::DOMElement& e,
               ::xml_schema::flags f,
               ::xml_schema::container* c)
: ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
  x_ (this),
  y_ (this),
  z_ (this)
{
  if ((f & ::xml_schema::flags::base) == 0)
  {
    ::xsd::cxx::xml::dom::parser< char > p (e, true, false, false);
    this->parse (p, f);
  }
}

void double_vector::
parse (::xsd::cxx::xml::dom::parser< char >& p,
       ::xml_schema::flags f)
{
  for (; p.more_content (); p.next_content (false))
  {
    const ::xercesc::DOMElement& i (p.cur_element ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (i));

    // x
    //
    if (n.name () == "x" && n.namespace_ ().empty ())
    {
      ::std::unique_ptr< x_type > r (
        x_traits::create (i, f, this));

      if (!x_.present ())
      {
        this->x_.set (::std::move (r));
        continue;
      }
    }

    // y
    //
    if (n.name () == "y" && n.namespace_ ().empty ())
    {
      ::std::unique_ptr< y_type > r (
        y_traits::create (i, f, this));

      if (!y_.present ())
      {
        this->y_.set (::std::move (r));
        continue;
      }
    }

    // z
    //
    if (n.name () == "z" && n.namespace_ ().empty ())
    {
      ::std::unique_ptr< z_type > r (
        z_traits::create (i, f, this));

      if (!z_.present ())
      {
        this->z_.set (::std::move (r));
        continue;
      }
    }

    break;
  }

  if (!x_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "x",
      "");
  }

  if (!y_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "y",
      "");
  }

  if (!z_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "z",
      "");
  }
}

double_vector* double_vector::
_clone (::xml_schema::flags f,
        ::xml_schema::container* c) const
{
  return new class double_vector (*this, f, c);
}

double_vector& double_vector::
operator= (const double_vector& x)
{
  if (this != &x)
  {
    static_cast< ::xml_schema::type& > (*this) = x;
    this->x_ = x.x_;
    this->y_ = x.y_;
    this->z_ = x.z_;
  }

  return *this;
}

double_vector::
~double_vector ()
{
}

// integer_vector
//

integer_vector::
integer_vector (const x_type& x,
                const y_type& y,
                const z_type& z)
: ::xml_schema::type (),
  x_ (x, this),
  y_ (y, this),
  z_ (z, this)
{
}

integer_vector::
integer_vector (const integer_vector& x,
                ::xml_schema::flags f,
                ::xml_schema::container* c)
: ::xml_schema::type (x, f, c),
  x_ (x.x_, f, this),
  y_ (x.y_, f, this),
  z_ (x.z_, f, this)
{
}

integer_vector::
integer_vector (const ::xercesc::DOMElement& e,
                ::xml_schema::flags f,
                ::xml_schema::container* c)
: ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
  x_ (this),
  y_ (this),
  z_ (this)
{
  if ((f & ::xml_schema::flags::base) == 0)
  {
    ::xsd::cxx::xml::dom::parser< char > p (e, true, false, false);
    this->parse (p, f);
  }
}

void integer_vector::
parse (::xsd::cxx::xml::dom::parser< char >& p,
       ::xml_schema::flags f)
{
  for (; p.more_content (); p.next_content (false))
  {
    const ::xercesc::DOMElement& i (p.cur_element ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (i));

    // x
    //
    if (n.name () == "x" && n.namespace_ ().empty ())
    {
      ::std::unique_ptr< x_type > r (
        x_traits::create (i, f, this));

      if (!x_.present ())
      {
        this->x_.set (::std::move (r));
        continue;
      }
    }

    // y
    //
    if (n.name () == "y" && n.namespace_ ().empty ())
    {
      ::std::unique_ptr< y_type > r (
        y_traits::create (i, f, this));

      if (!y_.present ())
      {
        this->y_.set (::std::move (r));
        continue;
      }
    }

    // z
    //
    if (n.name () == "z" && n.namespace_ ().empty ())
    {
      ::std::unique_ptr< z_type > r (
        z_traits::create (i, f, this));

      if (!z_.present ())
      {
        this->z_.set (::std::move (r));
        continue;
      }
    }

    break;
  }

  if (!x_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "x",
      "");
  }

  if (!y_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "y",
      "");
  }

  if (!z_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "z",
      "");
  }
}

integer_vector* integer_vector::
_clone (::xml_schema::flags f,
        ::xml_schema::container* c) const
{
  return new class integer_vector (*this, f, c);
}

integer_vector& integer_vector::
operator= (const integer_vector& x)
{
  if (this != &x)
  {
    static_cast< ::xml_schema::type& > (*this) = x;
    this->x_ = x.x_;
    this->y_ = x.y_;
    this->z_ = x.z_;
  }

  return *this;
}

integer_vector::
~integer_vector ()
{
}

// cuboid
//

cuboid::
cuboid (const coordinates_type& coordinates,
        const particles_per_dimension_type& particles_per_dimension,
        const distance_particles_type& distance_particles,
        const mass_type& mass,
        const velocity_type& velocity)
: ::xml_schema::type (),
  coordinates_ (coordinates, this),
  particles_per_dimension_ (particles_per_dimension, this),
  distance_particles_ (distance_particles, this),
  mass_ (mass, this),
  velocity_ (velocity, this)
{
}

cuboid::
cuboid (::std::unique_ptr< coordinates_type > coordinates,
        ::std::unique_ptr< particles_per_dimension_type > particles_per_dimension,
        const distance_particles_type& distance_particles,
        const mass_type& mass,
        ::std::unique_ptr< velocity_type > velocity)
: ::xml_schema::type (),
  coordinates_ (std::move (coordinates), this),
  particles_per_dimension_ (std::move (particles_per_dimension), this),
  distance_particles_ (distance_particles, this),
  mass_ (mass, this),
  velocity_ (std::move (velocity), this)
{
}

cuboid::
cuboid (const cuboid& x,
        ::xml_schema::flags f,
        ::xml_schema::container* c)
: ::xml_schema::type (x, f, c),
  coordinates_ (x.coordinates_, f, this),
  particles_per_dimension_ (x.particles_per_dimension_, f, this),
  distance_particles_ (x.distance_particles_, f, this),
  mass_ (x.mass_, f, this),
  velocity_ (x.velocity_, f, this)
{
}

cuboid::
cuboid (const ::xercesc::DOMElement& e,
        ::xml_schema::flags f,
        ::xml_schema::container* c)
: ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
  coordinates_ (this),
  particles_per_dimension_ (this),
  distance_particles_ (this),
  mass_ (this),
  velocity_ (this)
{
  if ((f & ::xml_schema::flags::base) == 0)
  {
    ::xsd::cxx::xml::dom::parser< char > p (e, true, false, false);
    this->parse (p, f);
  }
}

void cuboid::
parse (::xsd::cxx::xml::dom::parser< char >& p,
       ::xml_schema::flags f)
{
  for (; p.more_content (); p.next_content (false))
  {
    const ::xercesc::DOMElement& i (p.cur_element ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (i));

    // coordinates
    //
    if (n.name () == "coordinates" && n.namespace_ ().empty ())
    {
      ::std::unique_ptr< coordinates_type > r (
        coordinates_traits::create (i, f, this));

      if (!coordinates_.present ())
      {
        this->coordinates_.set (::std::move (r));
        continue;
      }
    }

    // particles_per_dimension
    //
    if (n.name () == "particles_per_dimension" && n.namespace_ ().empty ())
    {
      ::std::unique_ptr< particles_per_dimension_type > r (
        particles_per_dimension_traits::create (i, f, this));

      if (!particles_per_dimension_.present ())
      {
        this->particles_per_dimension_.set (::std::move (r));
        continue;
      }
    }

    // distance_particles
    //
    if (n.name () == "distance_particles" && n.namespace_ ().empty ())
    {
      ::std::unique_ptr< distance_particles_type > r (
        distance_particles_traits::create (i, f, this));

      if (!distance_particles_.present ())
      {
        this->distance_particles_.set (::std::move (r));
        continue;
      }
    }

    // mass
    //
    if (n.name () == "mass" && n.namespace_ ().empty ())
    {
      ::std::unique_ptr< mass_type > r (
        mass_traits::create (i, f, this));

      if (!mass_.present ())
      {
        this->mass_.set (::std::move (r));
        continue;
      }
    }

    // velocity
    //
    if (n.name () == "velocity" && n.namespace_ ().empty ())
    {
      ::std::unique_ptr< velocity_type > r (
        velocity_traits::create (i, f, this));

      if (!velocity_.present ())
      {
        this->velocity_.set (::std::move (r));
        continue;
      }
    }

    break;
  }

  if (!coordinates_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "coordinates",
      "");
  }

  if (!particles_per_dimension_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "particles_per_dimension",
      "");
  }

  if (!distance_particles_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "distance_particles",
      "");
  }

  if (!mass_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "mass",
      "");
  }

  if (!velocity_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "velocity",
      "");
  }
}

cuboid* cuboid::
_clone (::xml_schema::flags f,
        ::xml_schema::container* c) const
{
  return new class cuboid (*this, f, c);
}

cuboid& cuboid::
operator= (const cuboid& x)
{
  if (this != &x)
  {
    static_cast< ::xml_schema::type& > (*this) = x;
    this->coordinates_ = x.coordinates_;
    this->particles_per_dimension_ = x.particles_per_dimension_;
    this->distance_particles_ = x.distance_particles_;
    this->mass_ = x.mass_;
    this->velocity_ = x.velocity_;
  }

  return *this;
}

cuboid::
~cuboid ()
{
}

// cuboid_cluster
//

cuboid_cluster::
cuboid_cluster ()
: ::xml_schema::type (),
  cuboid_ (this)
{
}

cuboid_cluster::
cuboid_cluster (const cuboid_cluster& x,
                ::xml_schema::flags f,
                ::xml_schema::container* c)
: ::xml_schema::type (x, f, c),
  cuboid_ (x.cuboid_, f, this)
{
}

cuboid_cluster::
cuboid_cluster (const ::xercesc::DOMElement& e,
                ::xml_schema::flags f,
                ::xml_schema::container* c)
: ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
  cuboid_ (this)
{
  if ((f & ::xml_schema::flags::base) == 0)
  {
    ::xsd::cxx::xml::dom::parser< char > p (e, true, false, false);
    this->parse (p, f);
  }
}

void cuboid_cluster::
parse (::xsd::cxx::xml::dom::parser< char >& p,
       ::xml_schema::flags f)
{
  for (; p.more_content (); p.next_content (false))
  {
    const ::xercesc::DOMElement& i (p.cur_element ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (i));

    // cuboid
    //
    if (n.name () == "cuboid" && n.namespace_ ().empty ())
    {
      ::std::unique_ptr< cuboid_type > r (
        cuboid_traits::create (i, f, this));

      this->cuboid_.push_back (::std::move (r));
      continue;
    }

    break;
  }
}

cuboid_cluster* cuboid_cluster::
_clone (::xml_schema::flags f,
        ::xml_schema::container* c) const
{
  return new class cuboid_cluster (*this, f, c);
}

cuboid_cluster& cuboid_cluster::
operator= (const cuboid_cluster& x)
{
  if (this != &x)
  {
    static_cast< ::xml_schema::type& > (*this) = x;
    this->cuboid_ = x.cuboid_;
  }

  return *this;
}

cuboid_cluster::
~cuboid_cluster ()
{
}

// particle
//

particle::
particle (const coordinates_type& coordinates,
          const velocity_type& velocity,
          const mass_type& mass)
: ::xml_schema::type (),
  coordinates_ (coordinates, this),
  velocity_ (velocity, this),
  mass_ (mass, this)
{
}

particle::
particle (::std::unique_ptr< coordinates_type > coordinates,
          ::std::unique_ptr< velocity_type > velocity,
          const mass_type& mass)
: ::xml_schema::type (),
  coordinates_ (std::move (coordinates), this),
  velocity_ (std::move (velocity), this),
  mass_ (mass, this)
{
}

particle::
particle (const particle& x,
          ::xml_schema::flags f,
          ::xml_schema::container* c)
: ::xml_schema::type (x, f, c),
  coordinates_ (x.coordinates_, f, this),
  velocity_ (x.velocity_, f, this),
  mass_ (x.mass_, f, this)
{
}

particle::
particle (const ::xercesc::DOMElement& e,
          ::xml_schema::flags f,
          ::xml_schema::container* c)
: ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
  coordinates_ (this),
  velocity_ (this),
  mass_ (this)
{
  if ((f & ::xml_schema::flags::base) == 0)
  {
    ::xsd::cxx::xml::dom::parser< char > p (e, true, false, false);
    this->parse (p, f);
  }
}

void particle::
parse (::xsd::cxx::xml::dom::parser< char >& p,
       ::xml_schema::flags f)
{
  for (; p.more_content (); p.next_content (false))
  {
    const ::xercesc::DOMElement& i (p.cur_element ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (i));

    // coordinates
    //
    if (n.name () == "coordinates" && n.namespace_ ().empty ())
    {
      ::std::unique_ptr< coordinates_type > r (
        coordinates_traits::create (i, f, this));

      if (!coordinates_.present ())
      {
        this->coordinates_.set (::std::move (r));
        continue;
      }
    }

    // velocity
    //
    if (n.name () == "velocity" && n.namespace_ ().empty ())
    {
      ::std::unique_ptr< velocity_type > r (
        velocity_traits::create (i, f, this));

      if (!velocity_.present ())
      {
        this->velocity_.set (::std::move (r));
        continue;
      }
    }

    // mass
    //
    if (n.name () == "mass" && n.namespace_ ().empty ())
    {
      ::std::unique_ptr< mass_type > r (
        mass_traits::create (i, f, this));

      if (!mass_.present ())
      {
        this->mass_.set (::std::move (r));
        continue;
      }
    }

    break;
  }

  if (!coordinates_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "coordinates",
      "");
  }

  if (!velocity_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "velocity",
      "");
  }

  if (!mass_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "mass",
      "");
  }
}

particle* particle::
_clone (::xml_schema::flags f,
        ::xml_schema::container* c) const
{
  return new class particle (*this, f, c);
}

particle& particle::
operator= (const particle& x)
{
  if (this != &x)
  {
    static_cast< ::xml_schema::type& > (*this) = x;
    this->coordinates_ = x.coordinates_;
    this->velocity_ = x.velocity_;
    this->mass_ = x.mass_;
  }

  return *this;
}

particle::
~particle ()
{
}

// particle_cluster
//

particle_cluster::
particle_cluster ()
: ::xml_schema::type (),
  particle_ (this)
{
}

particle_cluster::
particle_cluster (const particle_cluster& x,
                  ::xml_schema::flags f,
                  ::xml_schema::container* c)
: ::xml_schema::type (x, f, c),
  particle_ (x.particle_, f, this)
{
}

particle_cluster::
particle_cluster (const ::xercesc::DOMElement& e,
                  ::xml_schema::flags f,
                  ::xml_schema::container* c)
: ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
  particle_ (this)
{
  if ((f & ::xml_schema::flags::base) == 0)
  {
    ::xsd::cxx::xml::dom::parser< char > p (e, true, false, false);
    this->parse (p, f);
  }
}

void particle_cluster::
parse (::xsd::cxx::xml::dom::parser< char >& p,
       ::xml_schema::flags f)
{
  for (; p.more_content (); p.next_content (false))
  {
    const ::xercesc::DOMElement& i (p.cur_element ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (i));

    // particle
    //
    if (n.name () == "particle" && n.namespace_ ().empty ())
    {
      ::std::unique_ptr< particle_type > r (
        particle_traits::create (i, f, this));

      this->particle_.push_back (::std::move (r));
      continue;
    }

    break;
  }
}

particle_cluster* particle_cluster::
_clone (::xml_schema::flags f,
        ::xml_schema::container* c) const
{
  return new class particle_cluster (*this, f, c);
}

particle_cluster& particle_cluster::
operator= (const particle_cluster& x)
{
  if (this != &x)
  {
    static_cast< ::xml_schema::type& > (*this) = x;
    this->particle_ = x.particle_;
  }

  return *this;
}

particle_cluster::
~particle_cluster ()
{
}

// input_particles
//

input_particles::
input_particles ()
: ::xml_schema::type (),
  particle_file_ (this),
  cuboids_file_ (this),
  cuboids_ (this),
  particles_ (this)
{
}

input_particles::
input_particles (const input_particles& x,
                 ::xml_schema::flags f,
                 ::xml_schema::container* c)
: ::xml_schema::type (x, f, c),
  particle_file_ (x.particle_file_, f, this),
  cuboids_file_ (x.cuboids_file_, f, this),
  cuboids_ (x.cuboids_, f, this),
  particles_ (x.particles_, f, this)
{
}

input_particles::
input_particles (const ::xercesc::DOMElement& e,
                 ::xml_schema::flags f,
                 ::xml_schema::container* c)
: ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
  particle_file_ (this),
  cuboids_file_ (this),
  cuboids_ (this),
  particles_ (this)
{
  if ((f & ::xml_schema::flags::base) == 0)
  {
    ::xsd::cxx::xml::dom::parser< char > p (e, true, false, false);
    this->parse (p, f);
  }
}

void input_particles::
parse (::xsd::cxx::xml::dom::parser< char >& p,
       ::xml_schema::flags f)
{
  for (; p.more_content (); p.next_content (false))
  {
    const ::xercesc::DOMElement& i (p.cur_element ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (i));

    // particle_file
    //
    if (n.name () == "particle_file" && n.namespace_ ().empty ())
    {
      ::std::unique_ptr< particle_file_type > r (
        particle_file_traits::create (i, f, this));

      if (!this->particle_file_)
      {
        this->particle_file_.set (::std::move (r));
        continue;
      }
    }

    // cuboids_file
    //
    if (n.name () == "cuboids_file" && n.namespace_ ().empty ())
    {
      ::std::unique_ptr< cuboids_file_type > r (
        cuboids_file_traits::create (i, f, this));

      if (!this->cuboids_file_)
      {
        this->cuboids_file_.set (::std::move (r));
        continue;
      }
    }

    // cuboids
    //
    if (n.name () == "cuboids" && n.namespace_ ().empty ())
    {
      ::std::unique_ptr< cuboids_type > r (
        cuboids_traits::create (i, f, this));

      if (!this->cuboids_)
      {
        this->cuboids_.set (::std::move (r));
        continue;
      }
    }

    // particles
    //
    if (n.name () == "particles" && n.namespace_ ().empty ())
    {
      ::std::unique_ptr< particles_type > r (
        particles_traits::create (i, f, this));

      if (!this->particles_)
      {
        this->particles_.set (::std::move (r));
        continue;
      }
    }

    break;
  }
}

input_particles* input_particles::
_clone (::xml_schema::flags f,
        ::xml_schema::container* c) const
{
  return new class input_particles (*this, f, c);
}

input_particles& input_particles::
operator= (const input_particles& x)
{
  if (this != &x)
  {
    static_cast< ::xml_schema::type& > (*this) = x;
    this->particle_file_ = x.particle_file_;
    this->cuboids_file_ = x.cuboids_file_;
    this->cuboids_ = x.cuboids_;
    this->particles_ = x.particles_;
  }

  return *this;
}

input_particles::
~input_particles ()
{
}

// molsimInput
//

molsimInput::
molsimInput (const delta_t_type& delta_t,
             const t_end_type& t_end,
             const filelocation_type& filelocation)
: ::xml_schema::type (),
  name_output_ (this),
  frequency_output_ (this),
  delta_t_ (delta_t, this),
  t_end_ (t_end, this),
  filelocation_ (filelocation, this)
{
}

molsimInput::
molsimInput (const molsimInput& x,
             ::xml_schema::flags f,
             ::xml_schema::container* c)
: ::xml_schema::type (x, f, c),
  name_output_ (x.name_output_, f, this),
  frequency_output_ (x.frequency_output_, f, this),
  delta_t_ (x.delta_t_, f, this),
  t_end_ (x.t_end_, f, this),
  filelocation_ (x.filelocation_, f, this)
{
}

molsimInput::
molsimInput (const ::xercesc::DOMElement& e,
             ::xml_schema::flags f,
             ::xml_schema::container* c)
: ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
  name_output_ (this),
  frequency_output_ (this),
  delta_t_ (this),
  t_end_ (this),
  filelocation_ (this)
{
  if ((f & ::xml_schema::flags::base) == 0)
  {
    ::xsd::cxx::xml::dom::parser< char > p (e, true, false, false);
    this->parse (p, f);
  }
}

void molsimInput::
parse (::xsd::cxx::xml::dom::parser< char >& p,
       ::xml_schema::flags f)
{
  for (; p.more_content (); p.next_content (false))
  {
    const ::xercesc::DOMElement& i (p.cur_element ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (i));

    // name_output
    //
    if (n.name () == "name_output" && n.namespace_ ().empty ())
    {
      ::std::unique_ptr< name_output_type > r (
        name_output_traits::create (i, f, this));

      if (!this->name_output_)
      {
        this->name_output_.set (::std::move (r));
        continue;
      }
    }

    // frequency_output
    //
    if (n.name () == "frequency_output" && n.namespace_ ().empty ())
    {
      if (!this->frequency_output_)
      {
        this->frequency_output_.set (frequency_output_traits::create (i, f, this));
        continue;
      }
    }

    // delta_t
    //
    if (n.name () == "delta_t" && n.namespace_ ().empty ())
    {
      if (!delta_t_.present ())
      {
        this->delta_t_.set (delta_t_traits::create (i, f, this));
        continue;
      }
    }

    // t_end
    //
    if (n.name () == "t_end" && n.namespace_ ().empty ())
    {
      if (!t_end_.present ())
      {
        this->t_end_.set (t_end_traits::create (i, f, this));
        continue;
      }
    }

    // filelocation
    //
    if (n.name () == "filelocation" && n.namespace_ ().empty ())
    {
      ::std::unique_ptr< filelocation_type > r (
        filelocation_traits::create (i, f, this));

      if (!filelocation_.present ())
      {
        this->filelocation_.set (::std::move (r));
        continue;
      }
    }

    break;
  }

  if (!delta_t_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "delta_t",
      "");
  }

  if (!t_end_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "t_end",
      "");
  }

  if (!filelocation_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "filelocation",
      "");
  }
}

molsimInput* molsimInput::
_clone (::xml_schema::flags f,
        ::xml_schema::container* c) const
{
  return new class molsimInput (*this, f, c);
}

molsimInput& molsimInput::
operator= (const molsimInput& x)
{
  if (this != &x)
  {
    static_cast< ::xml_schema::type& > (*this) = x;
    this->name_output_ = x.name_output_;
    this->frequency_output_ = x.frequency_output_;
    this->delta_t_ = x.delta_t_;
    this->t_end_ = x.t_end_;
    this->filelocation_ = x.filelocation_;
  }

  return *this;
}

molsimInput::
~molsimInput ()
{
}

#include <istream>
#include <xsd/cxx/xml/sax/std-input-source.hxx>
#include <xsd/cxx/tree/error-handler.hxx>

::std::unique_ptr< ::molsimInput >
molsimInput_ (const ::std::string& u,
              ::xml_schema::flags f,
              const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0,
    (f & ::xml_schema::flags::keep_dom) == 0);

  ::xsd::cxx::tree::error_handler< char > h;

  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      u, h, p, f));

  h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

  return ::std::unique_ptr< ::molsimInput > (
    ::molsimInput_ (
      std::move (d), f | ::xml_schema::flags::own_dom, p));
}

::std::unique_ptr< ::molsimInput >
molsimInput_ (const ::std::string& u,
              ::xml_schema::error_handler& h,
              ::xml_schema::flags f,
              const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0,
    (f & ::xml_schema::flags::keep_dom) == 0);

  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      u, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  return ::std::unique_ptr< ::molsimInput > (
    ::molsimInput_ (
      std::move (d), f | ::xml_schema::flags::own_dom, p));
}

::std::unique_ptr< ::molsimInput >
molsimInput_ (const ::std::string& u,
              ::xercesc::DOMErrorHandler& h,
              ::xml_schema::flags f,
              const ::xml_schema::properties& p)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      u, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  return ::std::unique_ptr< ::molsimInput > (
    ::molsimInput_ (
      std::move (d), f | ::xml_schema::flags::own_dom, p));
}

::std::unique_ptr< ::molsimInput >
molsimInput_ (::std::istream& is,
              ::xml_schema::flags f,
              const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0,
    (f & ::xml_schema::flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is);
  return ::molsimInput_ (isrc, f, p);
}

::std::unique_ptr< ::molsimInput >
molsimInput_ (::std::istream& is,
              ::xml_schema::error_handler& h,
              ::xml_schema::flags f,
              const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0,
    (f & ::xml_schema::flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is);
  return ::molsimInput_ (isrc, h, f, p);
}

::std::unique_ptr< ::molsimInput >
molsimInput_ (::std::istream& is,
              ::xercesc::DOMErrorHandler& h,
              ::xml_schema::flags f,
              const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::sax::std_input_source isrc (is);
  return ::molsimInput_ (isrc, h, f, p);
}

::std::unique_ptr< ::molsimInput >
molsimInput_ (::std::istream& is,
              const ::std::string& sid,
              ::xml_schema::flags f,
              const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0,
    (f & ::xml_schema::flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
  return ::molsimInput_ (isrc, f, p);
}

::std::unique_ptr< ::molsimInput >
molsimInput_ (::std::istream& is,
              const ::std::string& sid,
              ::xml_schema::error_handler& h,
              ::xml_schema::flags f,
              const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::flags::dont_initialize) == 0,
    (f & ::xml_schema::flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
  return ::molsimInput_ (isrc, h, f, p);
}

::std::unique_ptr< ::molsimInput >
molsimInput_ (::std::istream& is,
              const ::std::string& sid,
              ::xercesc::DOMErrorHandler& h,
              ::xml_schema::flags f,
              const ::xml_schema::properties& p)
{
  ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
  return ::molsimInput_ (isrc, h, f, p);
}

::std::unique_ptr< ::molsimInput >
molsimInput_ (::xercesc::InputSource& i,
              ::xml_schema::flags f,
              const ::xml_schema::properties& p)
{
  ::xsd::cxx::tree::error_handler< char > h;

  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      i, h, p, f));

  h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

  return ::std::unique_ptr< ::molsimInput > (
    ::molsimInput_ (
      std::move (d), f | ::xml_schema::flags::own_dom, p));
}

::std::unique_ptr< ::molsimInput >
molsimInput_ (::xercesc::InputSource& i,
              ::xml_schema::error_handler& h,
              ::xml_schema::flags f,
              const ::xml_schema::properties& p)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      i, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  return ::std::unique_ptr< ::molsimInput > (
    ::molsimInput_ (
      std::move (d), f | ::xml_schema::flags::own_dom, p));
}

::std::unique_ptr< ::molsimInput >
molsimInput_ (::xercesc::InputSource& i,
              ::xercesc::DOMErrorHandler& h,
              ::xml_schema::flags f,
              const ::xml_schema::properties& p)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      i, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  return ::std::unique_ptr< ::molsimInput > (
    ::molsimInput_ (
      std::move (d), f | ::xml_schema::flags::own_dom, p));
}

::std::unique_ptr< ::molsimInput >
molsimInput_ (const ::xercesc::DOMDocument& doc,
              ::xml_schema::flags f,
              const ::xml_schema::properties& p)
{
  if (f & ::xml_schema::flags::keep_dom)
  {
    ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
      static_cast< ::xercesc::DOMDocument* > (doc.cloneNode (true)));

    return ::std::unique_ptr< ::molsimInput > (
      ::molsimInput_ (
        std::move (d), f | ::xml_schema::flags::own_dom, p));
  }

  const ::xercesc::DOMElement& e (*doc.getDocumentElement ());
  const ::xsd::cxx::xml::qualified_name< char > n (
    ::xsd::cxx::xml::dom::name< char > (e));

  if (n.name () == "molsimInput" &&
      n.namespace_ () == "")
  {
    ::std::unique_ptr< ::molsimInput > r (
      ::xsd::cxx::tree::traits< ::molsimInput, char >::create (
        e, f, 0));
    return r;
  }

  throw ::xsd::cxx::tree::unexpected_element < char > (
    n.name (),
    n.namespace_ (),
    "molsimInput",
    "");
}

::std::unique_ptr< ::molsimInput >
molsimInput_ (::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d,
              ::xml_schema::flags f,
              const ::xml_schema::properties&)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > c (
    ((f & ::xml_schema::flags::keep_dom) &&
     !(f & ::xml_schema::flags::own_dom))
    ? static_cast< ::xercesc::DOMDocument* > (d->cloneNode (true))
    : 0);

  ::xercesc::DOMDocument& doc (c.get () ? *c : *d);
  const ::xercesc::DOMElement& e (*doc.getDocumentElement ());

  const ::xsd::cxx::xml::qualified_name< char > n (
    ::xsd::cxx::xml::dom::name< char > (e));

  if (f & ::xml_schema::flags::keep_dom)
    doc.setUserData (::xml_schema::dom::tree_node_key,
                     (c.get () ? &c : &d),
                     0);

  if (n.name () == "molsimInput" &&
      n.namespace_ () == "")
  {
    ::std::unique_ptr< ::molsimInput > r (
      ::xsd::cxx::tree::traits< ::molsimInput, char >::create (
        e, f, 0));
    return r;
  }

  throw ::xsd::cxx::tree::unexpected_element < char > (
    n.name (),
    n.namespace_ (),
    "molsimInput",
    "");
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

